<?php
class Cylinder extends Circle {
    public $height;

    public function __construct($name, $radius, $height)
    {
        parent::__construct($name, $radius);
        $this->height = $height;
    }

    public function getHeight() {
        return $this->height;
    }

    public function calculateArea()
    {
        return parent::calculatePerimeter() * $this->height; // TODO: Change the autogenerated stub
    }

    public function calculatePerimeter()
    {
        return parent::calculatePerimeter() * $this->height + parent::calculateArea(); // TODO: Change the autogenerated stub
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "height= " .$this->getHeight(). '<br>';
    }
}